### ISSUE TITLE
Support comments locally

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#10]
It's great if we could support comments on the local machine for the developer without doing any additional work.
To add comments support normally, we have to enable following env vars. Here's how ideas to get them:
- STORYBOOK_CLOUD_URL - We could set something default for this.
- STORYBOOK_CLOUD_APPID - We could get this from user's GitHub org/repo
- STORYBOOK_CLOUD_DATABASE - We could get this from user's branch.

Other than that, we should smooth the local commenting process.
- If the user not loggedIn, we should allow him to login to Storybook Hub and come here.
- If the user loggedIn and no app found, we should ask him to create a one.

**Comment by thani-sh** [comment]
React Storybook sets following env variables which is enough to detect the app. It works fine for existing apps right now.

```
STORYBOOK_GIT_ORIGIN
STORYBOOK_GIT_BRANCH
```

Must handle the last case (app not available on Storybook Hub).

**Comment by arunoda** [comment]
This is fixed with #31
