### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#17]
Add a way to delete comments.
This is only allowed for the owner of the comment.

**Comment by thani-sh** [comment]
From `v2.3.0` database collections have a `del` method but it doesn't block other people from deleting comments. Created an issue on storybook-hub-backend about protecting documents form being modified by other users.

I'm working on a dataStore method to delete comments right now.

**Comment by arunoda** [comment]
@mnmtanish great.
I assume we can work on that protected feature soon.

**Comment by thani-sh** [comment]
Released `v1.5.0` with delete feature
