### ISSUE TITLE
Change the Screen when user not logged in

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#2]
Currently it'll looks like this:

<img width="1179" alt="screen shot 2016-10-06 at 11 42 44 am" src="https://cloud.githubusercontent.com/assets/50838/19142301/0dd72112-8bba-11e6-9b8a-321dafab3a93.png">

Change that button text to: "SignIn with Storybook Hub".
And send the user to: https://hub.getstorybook.io/sign-in

**Comment by kasunben** [comment]
Fixed with #12
