### ISSUE TITLE
Can't work with the storybook-addon-comments

### ISSUE THREAD

**Issue by Tevinthuku** [kadirahq/storybook-addon-comments#50]
`Uncaught Error: process.binding is not supported(…)`
This is the error Im getting when I add 
`import '@kadira/storybook-addon-comments/register';`

to my addon.js file

**Comment by arunoda** [comment]
Are you using the latest version of Storybook?

**Comment by Tevinthuku** [comment]
I think that was the problem. Thanks and sorry for the late response
