### ISSUE TITLE
Don't show my full name

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#6]
See: 
<img width="1188" alt="screen shot 2016-10-06 at 11 48 33 am" src="https://cloud.githubusercontent.com/assets/50838/19142406/da05485e-8bba-11e6-98b2-0c09000d8cd1.png">

Here, we don't need to show the full name. Just showing "Me" is fine. Or simply remove it altogether.
By doing that, we could get more space when the panel is in the right side like this:

<img width="810" alt="screen shot 2016-10-06 at 11 49 56 am" src="https://cloud.githubusercontent.com/assets/50838/19142443/1687a592-8bbb-11e6-928d-b990e3a2b581.png">

**Comment by kasunben** [comment]
Fixed with #15
