### ISSUE TITLE
Remove full date

### ISSUE THREAD

**Issue by arunoda** [kadirahq/storybook-addon-comments#7]
See the data next to the user's name. (In the comment item)
<img width="1188" alt="screen shot 2016-10-06 at 11 48 33 am" src="https://cloud.githubusercontent.com/assets/50838/19142464/3574b45e-8bbb-11e6-9080-9e1578e1e510.png">

That long. Show something like "2 days ago" instead.

**Comment by kasunben** [comment]
Fixed with #13
